---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: petclinic
spec:
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: "petclinic"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: petclinic
spec:
  selector:
    matchLabels:
      app: "petclinic"
  template:
    metadata:
      labels:
        app: "petclinic"
    spec:
      containers:
      - name: petclinic
        image: dev.registry.pivotal.io/library/petclinic